---
title: "Advisor Team Assessment Guidelines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

Each Tuesday the individuals on teams who are not presenting progress reports will serve on advisor teams.  Advisor teams are responsible for evaluating and providing constructive feedback to one of the presenting teams.  Your evaluation should follow the general structure described below:

**Executive Summary**

A 2-5 sentence summary of the current status of the project.  You might summarize important achievements, current concerns, or areas that need more work.  This should be written as if you could email it to the presenting team's client as an update on where the project.

**Goal Review**

A bulleted list describing each of the presenting team's goals.  Each bullet should begin with a score out of 10, with 0 indicating the goal was absent from the presentation and/or completely ignored by the team, and 10 indicating the goal was perfectly achieved with clear and abundant evidence of fulfillment.  After your score you should provide 1-3 sentences explaining why the particular score was warranted.

**Steering Advice**

A bulleted list of suggestions for the team to pursue prior to the next progress briefing.  For this you should draw upon your own areas of expertise and think about what things you'd be doing/changing if you were a member of the presenting team. (Note: there will be an advisor team take-over for one week later in the semester, so you will get a chance to actually take control of the project you are advising).

## Other Directions

- You are encouraged to interact with the presenting team *during* their presentation to help you construct an accurate evaluation.  This means asking for clarification when necessary, or asking probing questions when you need more details.
- You may also meet with the presenting team *after* their presentation to discuss elements of their project/presentation in greater detail.
- You should have your assessment completed by the *end of class*. At that point you should share it with the both the team and Prof. Miller.
- Your ratings/assessments *will not be used* to determine the presenting team's grade on their progress briefing.  Prof. Miller will evaluate the group independently.  This means you should be as honest as possible in your assessment.  It's better to give a group a low score and clearly signal where they need to improve rather than allowing them to continue underperforming.
- Finally, recognize that the effort you (as an advisor team member) put into your evaluation and feedback will have an impact on *your* grade. 

## Example 

**Executive Summary**

Group 4B shared progress in two main areas: a quality assessment of the time-series data, and an update of their current business understandings of driving simulator data.  At present they've identified two case files which need to be excluded or confirmed valid by the client due to irregularities.  They are currently working on joining subject disposition files with the validated time-series data.

**Goal Review**

- Goal #1 - Assess the quality of the time-series data as measured by an output file of position graphs for each subject during each event of interest. (restatement of goal)
    - Score: 5 - While the team did investigate the quality of the time-series data, their graphical analysis was incomplete and did not clearly support their claims about cases that needed to be confirmed valid by the client.
- Goal #2 - $\ldots$
    
**Steering Advice**

- A task/method/tool to consider, or something that should be revised
- Another task/method/tool to consider, or something that should be revised
- $\ldots$
