---
title: "Progress Reporting Guidelines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Description

Each progress report should take approximately 20 minutes with room for Q+A during and after.  It should focus on your team's current set of goal and you should begin by restating these goals before moving into a discussion of the progress you made towards them. 

You may use any format you'd like (PowerPoint, R Markdown, stuff pasted into a google doc), so long as the entire class is able to follow along and you don't get bogged down on inconsequential items.

Depending your goals, a good report might include:

- Clear and succinct information describing or updating your business understanding of your project
- Data visualizations or tables describing or updating your data understanding
- Pseudo-code or diagrams detailing your data preparation process 
- Descriptions, explanations, and results from the models/methods you applied

Regardless of your goals, good report should include:

- A brief reflection on things that went well, didn't go well, or took longer than expected
- A brief reflection on how feasible your team's goals were
- A brief discussion of where your project might go next

Additionally, if you met with your client recently you should provide a brief summary of that meeting in your report.

### Scoring

Each progress report will be scored in two dimensions:

- A 1-10 rating of your report's overall quality measured by:
    - How well it met the guidelines above
    - How fluent and well-articulated it was
    - The degree of professionalism of the presenting group
- A 1-5 rating of your team's ability to construct and achieve short-term goals, measured by:
    - Were your goals clearly defined
    - Were your goals consist with your location in the data science life cycle
    - Did your presentation clearly indicate whether or not your goals were met